[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pyth_demo = "8xAgQUjq4yURfNbmxN2nf9gZ3NizaGUotUjTWCAWAjaY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/bilalafzal/.config/solana/id.json"

[scripts]
test = "dotenv -e .env.local -- yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_demo = "dotenv -e .env.local -- ts-node migrations/pyth-demo.ts"

[[test.genesis]]
address = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"
program = "./dep/solana_receiver_program.so"

[[test.genesis]]
address = "pythWSnswVUd12oZpeFP8e9CVaEqJg25g1Vtc2biRsT"
program = "./dep/price_feed_program.so"

[[test.genesis]]
address = "HDwcJBJXjL9FpJ7UBsYBtaDjsBUhuLCUYoz3zr8SWWaQ"
program = "./dep/wormhole_core_bridge_solana.so"